### ISSUE TITLE
Error on Windows 10: Can't find EditorSelectionSE.png

### ISSUE THREAD

**Issue by afefafafe** [fireclawthefox/FRAME#18]
Today I installed Frame from pypi and when trying to run it I encountered the following error 

OSError: Could not load texture: C:\Users\user\PycharmProjects\PiGamedev\venv\PIGAMEDEV\lib\site-packages\panda3d_frame\editors\EditorSelectionSE.png

I'm not sure why this error is happening as it appears EditorSelectionSE.png is in the folder.

OS: Windows 10
Python Version: 3.9

Here's the log file
[FRAME.log](https://github.com/fireclawthefox/FRAME/files/9872308/FRAME.log)

**Comment by fireclawthefox** [comment]
Hm, if the path is correct, could you check if you have enough permissions to access this file and/or folder?
I will try this on my windows machine later, I've never tried running it from a virtual environment though, maybe that has some more restrictions tied to it.

**Comment by fireclawthefox** [comment]
Found the issue. It's the windows path style again... Will push a fix soon.
